# Generated by Django 4.1.13 on 2024-10-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_alter_partners_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
