# Generated by Django 4.1.13 on 2024-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_delete_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
