# Generated by Django 4.1.13 on 2024-10-03 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_companies_profive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='image',
        ),
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profive',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
