# Generated by Django 4.1.13 on 2024-10-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_companies_image_companies_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companies',
        ),
        migrations.DeleteModel(
            name='Profive',
        ),
    ]
