# Generated by Django 4.1.13 on 2024-10-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_company_menuitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
