# Generated by Django 4.1.13 on 2024-10-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_menuitem_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
